# Generated by Django 4.1.3 on 2023-01-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_prize', models.FloatField()),
                ('discounted_prize', models.FloatField()),
                ('discription', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('MZ', 'maruti suzuki'), ('HY', 'maruti suzuki'), ('AD', 'maruti suzuki'), ('JR', 'maruti suzuki'), ('JP', 'maruti suzuki'), ('BM', 'maruti suzuki'), ('MS', 'maruti suzuki'), ('SK', 'maruti suzuki'), ('VO', 'maruti suzuki'), ('HO', 'maruti suzuki'), ('LM', 'maruti suzuki'), ('PE', 'maruti suzuki')], max_length=2)),
                ('product_images', models.ImageField(upload_to='product')),
            ],
        ),
    ]
