# Generated by Django 4.1.3 on 2023-01-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.AddField(
            model_name='cart',
            name='cust',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
