# Generated by Django 4.1.3 on 2023-01-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_orderplaced_payment_cart_cust_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cust',
        ),
    ]
