# Generated by Django 4.1.3 on 2023-01-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_payment_orderplaced_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
