# Generated by Django 4.1.3 on 2023-01-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payment_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cust',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
