# Generated by Django 4.1.3 on 2023-01-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cart_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cust',
        ),
    ]
